excluded:
- Carthage
- Pods
- DocsUITests
- libwebp
line_length: 10000
identifier_name:
min_length: 1
error: 4
excluded:
- id
- URL
disabled_rules:
- trailing_whitespace
- closure_parameter_position
- multiple_closures_with_trailing_closure
- todo
